# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

def run_build
  build_app(
    workspace: "TheLiturgists.xcworkspace",
    scheme: "TheLiturgists",
  )
end

platform :ios do
  desc "Run a new beta build (but don't upload it)"
  lane :build do
    run_build
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    run_build
    upload_to_testflight
  end
end
