# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

require 'json'

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

api_key = nil

def run_build
  build_app(
    workspace: "TheLiturgists.xcworkspace",
    scheme: "TheLiturgists",
  )
end

platform :ios do
  before_all do
    if ENV.key? 'CI'
      setup_ci
      api_key = app_store_connect_api_key(
        in_house: false,
        is_key_content_base64: true
      )
      match(type: 'appstore', api_key: api_key)
    end
  end

  desc "Run a new beta build (but don't upload it)"
  lane :build do
    run_build
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    run_build

    # This code runs in the ios/fastlane dir
    version = JSON.parse(File.read('../../package.json'))["version"]
    changelog = read_changelog(
      # This function runs in the ios dir, so look one level up
      changelog_path: "../CHANGELOG.md",
      section_identifier: "[#{version}]",
      excluded_markdown_elements: [],
    )
    if changelog.empty?
      changelog = "Internal improvements and fixes only; (hopefully) nothing you'll notice."
    end
    upload_to_testflight(changelog: changelog, api_key: api_key)
  end
end
