#!/bin/bash -e

if [[ -z $EXPO_RELEASE_CHANNEL ]]; then
    if [[ -n $GITHUB_REF ]]; then
        source ./ci/common.inc
        EXPO_RELEASE_CHANNEL=$(get_release_channel $GITHUB_REF)
    else
        EXPO_RELEASE_CHANNEL=default
    fi
fi
manifest="android/app/src/main/AndroidManifest.xml"
manifest_template="${manifest}.template"
cp -f $manifest_template $manifest
sed -i.bak "s/android:name=\"expo.modules.updates.EXPO_RELEASE_CHANNEL\" android:value=\".*\"/android:name=\"expo.modules.updates.EXPO_RELEASE_CHANNEL\" android:value=\"${EXPO_RELEASE_CHANNEL}\"/" ${manifest}

npx jetify
