# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

def run_build
  gradle(task: "clean bundleRelease")
end

platform :android do
  lane :build do
    run_build
  end

  desc "Submit a new Beta Build to Google Play"
  lane :beta do
    run_build
    upload_to_play_store(skip_upload_apk: true, track: 'beta')
  end

  desc "Deploy a new version to the Google Play Store"
  lane :deploy do
    run_build
    upload_to_play_store(skip_upload_apk: true)
  end
end
