name: Deploy to beta testing

on:
  push:
    tags:
      - 'v*-beta.*'

jobs:
  get_version:
    runs-on: ubuntu-latest
    name: Get release version
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1 
        with:
          node-version: '12'

      - run: echo ::set_output name=version::$(node -e 'console.log(require("./package.json").version)')
        id: get_version
    outputs:
      version: ${{ steps.get_version.outputs.version }}

  deploy-ios:
    runs-on: macos-latest
    name: Deploy iOS beta to TestFlight
    environment:
      name: iOS Beta
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1 
        with:
          node-version: '12'

      - uses: ktmud/cached-dependencies@v1
        with:
          caches: ${{ github.workspace }}/.github/workflows/caches/ios.js
          bashlib: ${{ github.workspace }}/.github/workflows/bashlib/ios.sh
          parallel: true

      - uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.FASTLANE_MATCH_DEPLOY_PRIVATE_KEY }}
        
      - run: npm run ci:generate-app-config
      - run: |
          npm start 2>&1 >metro.log &
          $(npm bin)/wait-on http-get://localhost:8081
          npm run beta:ios
        name: Build and deploy
        env:
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          MATCH_PASSWORD: ${{ secrets.FASTLANE_MATCH_PASSWORD }}

      - name: Archive metro logs
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: metro logs (fastlane build, ios)
          path: metro.log

  deploy-android:
    runs-on: macos-latest
    name: Deploy Android beta to Google Play
    environment:
      name: Android Beta
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1 
        with:
          node-version: '12'

      - uses: ktmud/cached-dependencies@v1
        with:
          caches: ${{ github.workspace }}/.github/workflows/caches/android.js
          bashlib: ${{ github.workspace }}/.github/workflows/bashlib/android.sh
          parallel: true

      - run: npm run ci:generate-app-config
      - run: |
          echo "${{ secrets.ANDROID_RELEASE_KEYSTORE_BASE64 }}" | base64 --decode > android/keystores/release.keystore
          echo "${{ secrets.GOOGLE_PLAY_AUTH_JSON_CONTENT }}" > android/google-play.json
        name: Put deployment creds in place

      - run: |
          npm start 2>&1 >metro.log &
          $(npm bin)/wait-on http-get://localhost:8081
          npm run beta:android
        name: Build and deploy
        env:
          ANDROID_RELEASE_PASSWORD: ${{ secrets.ANDROID_RELEASE_PASSWORD }}

      - name: Archive metro logs
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: metro logs (fastlane build, android)
          path: metro.log

  github-release:
    runs-on: ubuntu-latest
    needs:
      - get_version
      - deploy-ios
      - deploy-android
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1 
        with:
          node-version: '12'

      - run: npm install -g rexreplace

      - name: extract changelog
        run: npm run ci:save-latest-changelog > CHANGELOG_LATEST.md
      - name: create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_name: Release ${{ needs.get_version.outputs.version }}
          tag_name: ${GITHUB_REF##*/}  # trim "refs/tags/"
          body_path: CHANGELOG_LATEST.md
