name: Close Pull Request

# only trigger on pull request closed events
on:
  pull_request:
    types: 
      - closed

jobs:
  close:
    name: Unpublish Expo release channel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          # Use the PR ref here, which exists even after the branch is deleted
          ref: refs/pull/${{ github.event.pull_request.number }}/head

      # Here, however, we need the branch name, since that's what we use
      # to name the expo release channel
      - run: ./ci/unpublish-expo-release-channel.sh ${{ github.event.pull_request.head.ref }}
